/**
 * The front end's demo dataset, used whenever the API is not reachable and in
 * VITE_DATA_MODE=static without exported files.
 *
 * DEMO DATA: demo-data.json is generated by pipeline/demo_route.py. Building
 * footprints, streets and services are real OpenStreetMap geometry; the walks,
 * AI readings, statuses and answers are invented to show the product. Buildings
 * are labelled by capture order, never by a real house number.
 */
import demo from "./demo-data.json";
import { displayStatus } from "../lib/status";
import type {
  AgentEvent,
  Award,
  Badge,
  Building,
  BuildingServicesResponse,
  BuildingsGeoJson,
  ContextBuildingsGeoJson,
  EvalResult,
  NearbyPoi,
  SimilarBuilding,
  StreetSummary,
  TimedAgentEvent,
  Walk,
  Walker,
  WalkerProfileResponse,
  WalkerStats,
} from "../lib/types";

export const TALBOT_STREET = "Talbot Street";
export const DEFAULT_MOCK_WALKER_ID = demo.walker.id;
export const DEMO_NOTE = demo.note;

export type StreetCamera = { center: [number, number]; zoom: number; pitch: number; bearing: number };
export const demoCameras = demo.cameras as unknown as Record<string, StreetCamera>;

export const mockBuildings: Building[] = (demo.buildings as unknown as Building[]).map((b) => ({
  ...b,
  display_status: displayStatus(b),
}));

export const mockBuildingsById: Record<string, Building> = Object.fromEntries(mockBuildings.map((b) => [b.id, b]));

export const mockBuildingsGeoJson: BuildingsGeoJson = {
  type: "FeatureCollection",
  features: mockBuildings.map((b) => ({
    type: "Feature" as const,
    id: b.id,
    geometry: (b.footprint ?? b.location)!,
    properties: b,
  })),
};

/** The map draws surrounding buildings from vector tiles, so no context file is needed. */
export const mockContextBuildings: ContextBuildingsGeoJson = { type: "FeatureCollection", features: [] };

export const mockServicesByBuilding = demo.services as unknown as Record<string, BuildingServicesResponse>;
export const mockNearbyPoisByBuilding: Record<string, NearbyPoi[]> = Object.fromEntries(
  Object.entries(mockServicesByBuilding).map(([id, s]) => [id, s.pois]),
);
export const mockSimilarByBuilding = demo.similar as unknown as Record<string, SimilarBuilding[]>;
export const mockReviewQueue = mockBuildings.filter((b) => b.display_status === "review");
export const mockEval = demo.eval as unknown as EvalResult;
export const mockBadges = demo.badges as unknown as Badge[];
export const mockWalker: Walker = demo.walker;
export const mockAwards = demo.awards as unknown as Award[];
export const mockWalks = demo.walks as unknown as Walk[];
export const mockStats = demo.stats as WalkerStats;

export const mockWalkerProfile: WalkerProfileResponse = {
  walker: mockWalker,
  stats: mockStats,
  awards: mockAwards,
  progress: demo.progress as WalkerProfileResponse["progress"],
};

export function summaryFor(buildings: Building[]): StreetSummary {
  const statuses = buildings.map(displayStatus);
  return {
    total: buildings.length,
    processed: buildings.filter((b) => Boolean(b.models.vision)).length,
    likely_underused: statuses.filter((s) => s === "likely_underused").length,
    review: statuses.filter((s) => s === "review").length,
    confirmed: statuses.filter((s) => s === "confirmed").length,
    home: statuses.filter((s) => s === "home").length,
  };
}

export const mockStreetSummary = summaryFor(mockBuildings.filter((b) => b.street === TALBOT_STREET));

// ---------------------------------------------------------------- agent answers

const onStreet = (street: string) =>
  mockBuildings.filter((b) => b.street === street && b.rank !== null).sort((a, b) => (a.rank ?? 0) - (b.rank ?? 0));

/** The street's best candidate the agent should name first (never an already confirmed one). */
export const DEMO_TOP_ID =
  onStreet(TALBOT_STREET).find((b) => b.display_status === "likely_underused")?.id ?? onStreet(TALBOT_STREET)[0]?.id ?? "";
/** A building where the two model passes disagree, for the "a human decides" step. */
export const DEMO_DISAGREEMENT_ID =
  onStreet(TALBOT_STREET).find((b) => b.display_status === "review" && b.verifier && !b.verifier.agree)?.id ??
  mockReviewQueue[0]?.id ??
  "";

export const DEMO_QUESTIONS = [
  `Where on ${TALBOT_STREET} should we inspect first?`,
  `Why is ${DEMO_TOP_ID} ranked first?`,
  "Which buildings need a human check?",
  `Find facades similar to ${DEMO_TOP_ID}`,
  "What is the grant and where is the official FAQ?",
] as const;

type ToolStep = { name: string; args: Record<string, unknown>; db_op: string; ms: number; summary: string };

function transcript(steps: ToolStep[], answer: string): TimedAgentEvent[] {
  const events: TimedAgentEvent[] = [];
  let t = 420;
  steps.forEach((step, i) => {
    const id = `call_demo_${i + 1}`;
    events.push({ t_ms: t, event: "tool_call", data: { id, name: step.name, args: step.args } });
    t += step.ms + 260;
    events.push({ t_ms: t, event: "tool_result", data: { id, name: step.name, ms: step.ms, db_op: step.db_op, summary: step.summary } });
    t += 220;
  });
  t += 380;
  for (const chunk of answer.match(/\S+\s*/g) ?? []) {
    events.push({ t_ms: t, event: "delta", data: { text: chunk } });
    t += 34;
  }
  events.push({ t_ms: t + 60, event: "done", data: { text: answer } });
  return events;
}

const top = mockBuildingsById[DEMO_TOP_ID];
const near = (id: string) => mockServicesByBuilding[id]?.services;
const metres = (v: number | null | undefined) => (v === null || v === undefined ? "over 1 km" : `${v} m`);
const ranked = onStreet(TALBOT_STREET);
const second = ranked.find((b) => b.id !== DEMO_TOP_ID && b.display_status === "likely_underused");
const review = mockBuildings.filter((b) => b.display_status === "review").sort((a, b) => (a.rank ?? 0) - (b.rank ?? 0));
const similarToTop = mockSimilarByBuilding[DEMO_TOP_ID] ?? [];

function lower(s: string | null | undefined) {
  return s ? s.charAt(0).toLowerCase() + s.slice(1) : "";
}

export const mockAgentTranscripts: Record<string, TimedAgentEvent[]> = top
  ? {
      [DEMO_QUESTIONS[0]]: transcript(
        [
          { name: "street_candidates", args: { street: TALBOT_STREET, limit: 5 }, db_op: "find", ms: 12,
            summary: `5 of ${ranked.length} ranked buildings on ${TALBOT_STREET}: ` + ranked.slice(0, 5).map((b) => `#${b.rank} ${b.id}`).join(", ") },
          { name: "building", args: { id: top.id }, db_op: "find", ms: 9,
            summary: `${top.id}: ${top.display_status}, rank ${top.rank}, confidence ${top.confidence}` },
          { name: "services_nearby", args: { id: top.id }, db_op: "$geoNear", ms: 61,
            summary: `${top.id}: services score ${near(top.id)?.score}/5 within walking distance` },
        ],
        `Inspect ${top.id} first: rank ${top.rank} on ${TALBOT_STREET}, likely underused, confidence ${top.confidence}` +
          `${top.separate_entrance === "yes" ? ", with a separate street door" : ""}.\n` +
          `Evidence: ${lower(top.evidence)} Both model passes agree.\n` +
          `Services ${near(top.id)?.score}/5 within walking distance (bus ${metres(near(top.id)?.bus_m)}, grocery ${metres(near(top.id)?.grocery_m)}, GP or pharmacy ${metres(near(top.id)?.gp_or_pharmacy_m)}).\n` +
          (second ? `Next: ${second.id} (rank ${second.rank}), ${lower(second.evidence)}\n` : "") +
          "Every candidate still needs human verification before any action.",
      ),
      [DEMO_QUESTIONS[1]]: transcript(
        [
          { name: "building", args: { id: top.id }, db_op: "find", ms: 8,
            summary: `${top.id}: ${top.display_status}, rank ${top.rank}, confidence ${top.confidence}` },
          { name: "services_nearby", args: { id: top.id }, db_op: "$geoNear", ms: 57,
            summary: `${top.id}: services score ${near(top.id)?.score}/5 within walking distance` },
        ],
        `${top.id} is rank ${top.rank} because both model passes read it as likely underused (confidence ${top.confidence}). ` +
          `Evidence: ${lower(top.evidence)} The independent verifier, looking only at the upper floors, saw the same signs. ` +
          `${top.separate_entrance === "yes" ? "It also has a separate street door, which ranks it higher. " : ""}` +
          `Services ${near(top.id)?.score}/5 within walking distance. It is a candidate for inspection; a human must verify it first.`,
      ),
      [DEMO_QUESTIONS[2]]: transcript(
        [
          { name: "review_queue", args: {}, db_op: "find", ms: 10,
            summary: `${review.length} buildings need a human check: ` + review.map((b) => b.id).join(", ") },
        ],
        `${review.length} buildings are waiting for a human decision:\n` +
          review
            .map((b) =>
              `• ${b.id} (rank ${b.rank}): ` +
              (b.verifier && !b.verifier.agree
                ? `the passes disagree, the verifier read ${b.verifier.status.replaceAll("_", " ")}.`
                : `low confidence (${b.confidence}).`),
            )
            .join("\n") +
          "\nA human decides each one; the agent only recommends.",
      ),
      [DEMO_QUESTIONS[3]]: transcript(
        [
          { name: "similar_facades", args: { id: top.id, k: 3 }, db_op: "$vectorSearch", ms: 38,
            summary: `3 facades similar to ${top.id}` },
        ],
        `Facades that read like ${top.id}:\n` +
          similarToTop.slice(0, 3).map((s) => `• ${s.id}, similarity ${Math.round(s.score * 100)}%, ${s.display_status.replaceAll("_", " ")}`).join("\n") +
          "\nSimilar signals are a reason to look, not a finding.",
      ),
      [DEMO_QUESTIONS[4]]: transcript(
        [{ name: "grant_info", args: {}, db_op: "static", ms: 0, summary: "Grant amounts and the official FAQ link" }],
        "The Vacant Above the Shop grant (launched April 2026) offers €95,000 for one unit, €115,000 for two and " +
          "€135,000 for three or more, plus up to €25,000 from SEAI for energy upgrades. The official FAQ is at " +
          "https://www.sdcc.ie/en/services/housing/vacant-homes/vacant-above-the-shop-grant-faqs.pdf. " +
          "Whether a building qualifies is the council's decision under that FAQ.",
      ),
    }
  : {};

export const MOCK_AGENT_QUESTION = DEMO_QUESTIONS[0];
export const mockAgentTranscript = mockAgentTranscripts[MOCK_AGENT_QUESTION] ?? [];

const normalize = (q: string) => q.trim().toLowerCase().replace(/\s+/g, " ").replace(/[?!. ]+$/, "");

export function getMockAgentTranscript(question: string): TimedAgentEvent[] {
  const match = Object.keys(mockAgentTranscripts).find((q) => normalize(q) === normalize(question));
  return mockAgentTranscripts[match ?? MOCK_AGENT_QUESTION] ?? [];
}

export function getMockBuilding(id: string): Building | undefined {
  return mockBuildingsById[id];
}

export function getMockSimilar(id: string, k = 5): SimilarBuilding[] {
  return (mockSimilarByBuilding[id] ?? []).slice(0, Math.max(1, Math.min(k, 20)));
}

/** Deep-copy fixtures before a static-mode write mutates them. */
export function cloneMockData<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

/** Full state seed for the static API adapter. */
export function createMockState() {
  return {
    buildings: cloneMockData(mockBuildings),
    awards: cloneMockData(mockAwards),
    walks: cloneMockData(mockWalks),
  };
}

/** Allows static callers to consume replayed events as the un-timed SSE union. */
export function untimedAgentEvent(event: TimedAgentEvent): AgentEvent {
  const { t_ms: _tMs, ...untimed } = event;
  return untimed as AgentEvent;
}
